[tool.bumpversion]
current_version = "0.1.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filepath = "VERSION"

[[tool.bumpversion.files]]
filepath = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

# [[tool.bumpversion.files]]
# filepath = "CMakeLists.txt"
# search = "project\\(\\s*([\\s\\S]*?)\\s+VERSION\\s+{current_version}([\\s\\S]*?)\\)"
# replace = "project(\\1 VERSION {new_version}\\2)"
