name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

env:
  FORCE_COLOR: 3

jobs:
  test:
    name: Test on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
        python-version: ['3.11', '3.12']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Lint with ruff (Python only)
      if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.11'
      run: |
        uv add ruff
        uv run ruff check src/ pytests/

    - name: Type check with mypy (Python only)
      if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.11'
      run: |
        uv add mypy
        uv run mypy src/cmsketch/ --ignore-missing-imports

    - name: Build C++ components
      run: |
        uv run python -c "
        import subprocess, sys, os
        
        # Create build directory
        os.makedirs('build', exist_ok=True)
        os.chdir('build')
        
        # Configure
        subprocess.run([
            'cmake', '..',
            '-DCMAKE_BUILD_TYPE=Release',
            '-DBUILD_TESTS=ON',
            '-DBUILD_PYTHON_BINDINGS=ON'
        ], check=True)
        
        # Build
        import platform
        if platform.system() == 'Windows':
            subprocess.run(['cmake', '--build', '.', '--config', 'Release'], check=True)
        else:
            subprocess.run(['make', '-j4'], check=True)
        "

    - name: Run C++ tests
      run: |
        cd build
        if [ "$RUNNER_OS" = "Windows" ]; then
          ./Release/cmsketch_tests || ./cmsketch_tests
        else
          ./cmsketch_tests
        fi
      shell: bash

    - name: Run Python tests
      run: |
        uv run pytest pytests/ -v --tb=short

    - name: Run benchmarks (smoke test)
      run: |
        cd benchmarks
        uv run python generate_data.py --count 100
        uv run python run.py --quick
